[package]
name = "garden"
version = "0.1.0"
authors = ["Andrey Kutejko <andy128k@gmail.com>", "Alexey Suslov <alexey.suslov@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
hex = "0.3.1"
failure = "0.1.1"
structopt = "0.2"
