name = "baby_names"
description = """
    Baby Names from Social Security Card Applications-National Level Data.
    The data (name, year of birth, sex and number) are from a 100 percent sample of Social Security card applications after 1879.
    """
version = "0.2.0"
homepage = "https://catalog.data.gov/dataset/baby-names-from-social-security-card-applications-national-level-data"
licence = "CC0"
files = [ { url = "https://www.ssa.gov/oact/babynames/names.zip", sha1 = "7311d142e7d246695f35b8726d92ea3ac84b0ea8" } ]
