name = "cifar-100"
description = """
    The CIFAR-100 dataset is a labeled subsets of the 80
    million tiny images dataset."""
version = "0.1.0"
homepage = "https://www.cs.toronto.edu/~kriz/cifar.html"
files = [ { url = "https://www.cs.toronto.edu/~kriz/cifar-100-binary.tar.gz", md5 = "03b5dce01913d631647c71ecec9e9cb8" } ]
