name = "cifar-10"
description = """
    The CIFAR-10 dataset is a labeled subsets of the 80
    million tiny images dataset."""
homepage = "https://www.cs.toronto.edu/~kriz/cifar.html"
files = [ { url = "https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz", md5 = "c32a1d4ab5d03f1284b67883e8d87530" } ]
