name = "mnist"
description = """
    The MNIST database of handwritten digits.
    """
homepage = "http://yann.lecun.com/exdb/mnist/"

[[files]]
url = "http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz"

[[files]]
url = "http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz"

[[files]]
url = "http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz"

[[files]]
url = "http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz"
