name = "cifar-100"
description = """
    The CIFAR-100 dataset is a labeled subsets of the 80
    million tiny images dataset. It consists of 60000
    32x32 colour images in 100 classes. Specifically, it
    has 100 classes containing 600 images each. There are
    500 training images and 100 testing images per class.
    The 100 classes in the CIFAR-100 are grouped into 20
    superclasses. Each image comes with a "fine" label
    (the class to which it belongs) and a "coarse" label
    (the superclass to which it belongs).
    The compressed archive file that contains the
    complete dataset is available for download at the
    offical website linked above; specifically the binary
    version for C programs. Note that using the data
    responsibly and respecting copyright remains your
    responsibility. The authors of CIFAR-100 aren't
    really explicit about any terms of use, so please
    read the website to make sure you want to download
    the dataset."""
homepage = "https://www.cs.toronto.edu/~kriz/cifar.html"
licence = "CC0"
files = [ { url = "https://www.cs.toronto.edu/~kriz/cifar-100-binary.tar.gz", sha256 = "58a81ae192c23a4be8b1804d68e518ed807d710a4eb253b1f2a199162a40d8ec" } ]
